ALL:
	gcc -o 08142236_conv2_debug.out -Ofast -w ./generated/GEMM_master.c ./generated/GEMM_nn.c ./generated/conv1.c ./generated/conv2.c ./generated/fc1.c ./generated/fc2.c ./generated/mp1.c ./generated/mp2.c ./generated/main.c  ./include/list.c ./include/utils.c ./include/image.c ./include/blas.c -lOpenCL -lm
